default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_PATH", "storage/production.sqlite3") %>
  queue:
    <<: *default
    database: <%= ENV.fetch("QUEUE_DATABASE_PATH", "storage/production_queue.sqlite3") %>
    migrations_paths: db/queue_migrate
