source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 6.0"
gem "rack-cors"
gem "json", "~> 2.15"
gem "solid_queue"
gem "webpush"

group :development, :test do
  gem "debug"
end

gem "rack-attack", "~> 6.8"
